<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'code' => 'AF', 'name' => 'Afghanistan', 'phone' => 93, 'currency_symbol' => '؋', 'currency' => 'AFN'],
            ['id' => 2, 'code' => 'AX', 'name' => 'Åland Islands', 'phone' => 358, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 3, 'code' => 'AL', 'name' => 'Albania', 'phone' => 355, 'currency_symbol' => 'Lek', 'currency' => 'ALL'],
            ['id' => 4, 'code' => 'DZ', 'name' => 'Algeria', 'phone' => 213, 'currency_symbol' => 'دج', 'currency' => 'DZD'],
            ['id' => 5, 'code' => 'AS', 'name' => 'American Samoa', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 6, 'code' => 'AD', 'name' => 'Andorra', 'phone' => 376, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 7, 'code' => 'AO', 'name' => 'Angola', 'phone' => 244, 'currency_symbol' => 'Kz', 'currency' => 'AOA'],
            ['id' => 8, 'code' => 'AI', 'name' => 'Anguilla', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 9, 'code' => 'AQ', 'name' => 'Antarctica', 'phone' => 672, 'currency_symbol' => '$', 'currency' => 'AAD'],
            ['id' => 10, 'code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 11, 'code' => 'AR', 'name' => 'Argentina', 'phone' => 54, 'currency_symbol' => '$', 'currency' => 'ARS'],
            ['id' => 12, 'code' => 'AM', 'name' => 'Armenia', 'phone' => 374, 'currency_symbol' => '֏', 'currency' => 'AMD'],
            ['id' => 13, 'code' => 'AW', 'name' => 'Aruba', 'phone' => 297, 'currency_symbol' => 'ƒ', 'currency' => 'AWG'],
            ['id' => 14, 'code' => 'AU', 'name' => 'Australia', 'phone' => 61, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 15, 'code' => 'AT', 'name' => 'Austria', 'phone' => 43, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 16, 'code' => 'AZ', 'name' => 'Azerbaijan', 'phone' => 994, 'currency_symbol' => 'm', 'currency' => 'AZN'],
            ['id' => 17, 'code' => 'BS', 'name' => 'Bahamas', 'phone' => 1, 'currency_symbol' => 'B$', 'currency' => 'BSD'],
            ['id' => 18, 'code' => 'BH', 'name' => 'Bahrain', 'phone' => 973, 'currency_symbol' => '.د.ب', 'currency' => 'BHD'],
            ['id' => 19, 'code' => 'BD', 'name' => 'Bangladesh', 'phone' => 880, 'currency_symbol' => '৳', 'currency' => 'BDT'],
            ['id' => 20, 'code' => 'BB', 'name' => 'Barbados', 'phone' => 1, 'currency_symbol' => 'Bds$', 'currency' => 'BBD'],
            ['id' => 21, 'code' => 'BY', 'name' => 'Belarus', 'phone' => 375, 'currency_symbol' => 'Br', 'currency' => 'BYN'],
            ['id' => 22, 'code' => 'BE', 'name' => 'Belgium', 'phone' => 32, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 23, 'code' => 'BZ', 'name' => 'Belize', 'phone' => 501, 'currency_symbol' => '$', 'currency' => 'BZD'],
            ['id' => 24, 'code' => 'BJ', 'name' => 'Benin', 'phone' => 229, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 25, 'code' => 'BM', 'name' => 'Bermuda', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'BMD'],
            ['id' => 26, 'code' => 'BT', 'name' => 'Bhutan', 'phone' => 975, 'currency_symbol' => 'Nu.', 'currency' => 'BTN'],
            ['id' => 27, 'code' => 'BO', 'name' => 'Bolivia (Plurinational State of)', 'phone' => 591, 'currency_symbol' => 'Bs.', 'currency' => 'BOB'],
            ['id' => 28, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone' => 387, 'currency_symbol' => 'KM', 'currency' => 'BAM'],
            ['id' => 29, 'code' => 'BW', 'name' => 'Botswana', 'phone' => 267, 'currency_symbol' => 'P', 'currency' => 'BWP'],
            ['id' => 30, 'code' => 'BV', 'name' => 'Bouvet Island', 'phone' => 55, 'currency_symbol' => 'kr', 'currency' => 'NOK'],
            ['id' => 31, 'code' => 'BR', 'name' => 'Brazil', 'phone' => 55, 'currency_symbol' => 'R$', 'currency' => 'BRL'],
            ['id' => 32, 'code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone' => 246, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 33, 'code' => 'BN', 'name' => 'Brunei Darussalam', 'phone' => 673, 'currency_symbol' => 'B$', 'currency' => 'BND'],
            ['id' => 34, 'code' => 'BG', 'name' => 'Bulgaria', 'phone' => 359, 'currency_symbol' => 'Лв.', 'currency' => 'BGN'],
            ['id' => 35, 'code' => 'BF', 'name' => 'Burkina Faso', 'phone' => 226, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 36, 'code' => 'BI', 'name' => 'Burundi', 'phone' => 257, 'currency_symbol' => 'FBu', 'currency' => 'BIF'],
            ['id' => 37, 'code' => 'CV', 'name' => 'Cabo Verde', 'phone' => 238, 'currency_symbol' => '$', 'currency' => 'CVE'],
            ['id' => 38, 'code' => 'KH', 'name' => 'Cambodia', 'phone' => 855, 'currency_symbol' => 'KHR', 'currency' => 'KHR'],
            ['id' => 39, 'code' => 'CM', 'name' => 'Cameroon', 'phone' => 237, 'currency_symbol' => 'FCFA', 'currency' => 'XAF'],
            ['id' => 40, 'code' => 'CA', 'name' => 'Canada', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'CAD'],
            ['id' => 41, 'code' => 'BQ', 'name' => 'Caribbean Netherlands', 'phone' => 599, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 42, 'code' => 'KY', 'name' => 'Cayman Islands', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'KYD'],
            ['id' => 43, 'code' => 'CF', 'name' => 'Central African Republic', 'phone' => 236, 'currency_symbol' => 'FCFA', 'currency' => 'XAF'],
            ['id' => 44, 'code' => 'TD', 'name' => 'Chad', 'phone' => 235, 'currency_symbol' => 'FCFA', 'currency' => 'XAF'],
            ['id' => 45, 'code' => 'CL', 'name' => 'Chile', 'phone' => 56, 'currency_symbol' => '$', 'currency' => 'CLP'],
            ['id' => 46, 'code' => 'CN', 'name' => 'China', 'phone' => 86, 'currency_symbol' => '¥', 'currency' => 'CNY'],
            ['id' => 47, 'code' => 'CX', 'name' => 'Christmas Island', 'phone' => 61, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 48, 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone' => 61, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 49, 'code' => 'CO', 'name' => 'Colombia', 'phone' => 57, 'currency_symbol' => '$', 'currency' => 'COP'],
            ['id' => 50, 'code' => 'KM', 'name' => 'Comoros', 'phone' => 269, 'currency_symbol' => 'CF', 'currency' => 'KMF'],
            ['id' => 51, 'code' => 'CG', 'name' => 'Congo', 'phone' => 242, 'currency_symbol' => 'FC', 'currency' => 'XAF'],
            ['id' => 52, 'code' => 'CD', 'name' => 'Congo, Democratic Republic of the', 'phone' => 243, 'currency_symbol' => 'FC', 'currency' => 'CDF'],
            ['id' => 53, 'code' => 'CK', 'name' => 'Cook Islands', 'phone' => 682, 'currency_symbol' => '$', 'currency' => 'NZD'],
            ['id' => 54, 'code' => 'CR', 'name' => 'Costa Rica', 'phone' => 506, 'currency_symbol' => '₡', 'currency' => 'CRC'],
            ['id' => 55, 'code' => 'HR', 'name' => 'Croatia', 'phone' => 385, 'currency_symbol' => 'kn', 'currency' => 'HRK'],
            ['id' => 56, 'code' => 'CU', 'name' => 'Cuba', 'phone' => 53, 'currency_symbol' => '$', 'currency' => 'CUP'],
            ['id' => 57, 'code' => 'CW', 'name' => 'Curaçao', 'phone' => 599, 'currency_symbol' => 'ƒ', 'currency' => 'ANG'],
            ['id' => 58, 'code' => 'CY', 'name' => 'Cyprus', 'phone' => 357, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 59, 'code' => 'CZ', 'name' => 'Czech Republic', 'phone' => 420, 'currency_symbol' => 'Kč', 'currency' => 'CZK'],
            ['id' => 60, 'code' => 'CI', 'name' => "Côte d'Ivoire", 'phone' => 225, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 61, 'code' => 'DK', 'name' => 'Denmark', 'phone' => 45, 'currency_symbol' => 'Kr.', 'currency' => 'DKK'],
            ['id' => 62, 'code' => 'DJ', 'name' => 'Djibouti', 'phone' => 253, 'currency_symbol' => 'Fdj', 'currency' => 'DJF'],
            ['id' => 63, 'code' => 'DM', 'name' => 'Dominica', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 64, 'code' => 'DO', 'name' => 'Dominican Republic', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'DOP'],
            ['id' => 65, 'code' => 'EC', 'name' => 'Ecuador', 'phone' => 593, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 66, 'code' => 'EG', 'name' => 'Egypt', 'phone' => 20, 'currency_symbol' => 'ج.م', 'currency' => 'EGP'],
            ['id' => 67, 'code' => 'SV', 'name' => 'El Salvador', 'phone' => 503, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 68, 'code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone' => 240, 'currency_symbol' => 'FCFA', 'currency' => 'XAF'],
            ['id' => 69, 'code' => 'ER', 'name' => 'Eritrea', 'phone' => 291, 'currency_symbol' => 'Nfk', 'currency' => 'ERN'],
            ['id' => 70, 'code' => 'EE', 'name' => 'Estonia', 'phone' => 372, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 71, 'code' => 'SZ', 'name' => 'Eswatini (Swaziland)', 'phone' => 268, 'currency_symbol' => 'E', 'currency' => 'SZL'],
            ['id' => 72, 'code' => 'ET', 'name' => 'Ethiopia', 'phone' => 251, 'currency_symbol' => 'Nkf', 'currency' => 'ETB'],
            ['id' => 73, 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'phone' => 500, 'currency_symbol' => '£', 'currency' => 'FKP'],
            ['id' => 74, 'code' => 'FO', 'name' => 'Faroe Islands', 'phone' => 298, 'currency_symbol' => 'Kr.', 'currency' => 'DKK'],
            ['id' => 75, 'code' => 'FJ', 'name' => 'Fiji', 'phone' => 679, 'currency_symbol' => 'FJ$', 'currency' => 'FJD'],
            ['id' => 76, 'code' => 'FI', 'name' => 'Finland', 'phone' => 358, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 77, 'code' => 'FR', 'name' => 'France', 'phone' => 33, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 78, 'code' => 'GF', 'name' => 'French Guiana', 'phone' => 594, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 79, 'code' => 'PF', 'name' => 'French Polynesia', 'phone' => 689, 'currency_symbol' => '₣', 'currency' => 'XPF'],
            ['id' => 80, 'code' => 'TF', 'name' => 'French Southern Territories', 'phone' => 262, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 81, 'code' => 'GA', 'name' => 'Gabon', 'phone' => 241, 'currency_symbol' => 'FCFA', 'currency' => 'XAF'],
            ['id' => 82, 'code' => 'GM', 'name' => 'Gambia', 'phone' => 220, 'currency_symbol' => 'D', 'currency' => 'GMD'],
            ['id' => 83, 'code' => 'GE', 'name' => 'Georgia', 'phone' => 995, 'currency_symbol' => 'ლ', 'currency' => 'GEL'],
            ['id' => 84, 'code' => 'DE', 'name' => 'Germany', 'phone' => 49, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 85, 'code' => 'GH', 'name' => 'Ghana', 'phone' => 233, 'currency_symbol' => 'GH₵', 'currency' => 'GHS'],
            ['id' => 86, 'code' => 'GI', 'name' => 'Gibraltar', 'phone' => 350, 'currency_symbol' => '£', 'currency' => 'GIP'],
            ['id' => 87, 'code' => 'GR', 'name' => 'Greece', 'phone' => 30, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 88, 'code' => 'GL', 'name' => 'Greenland', 'phone' => 299, 'currency_symbol' => 'Kr.', 'currency' => 'DKK'],
            ['id' => 89, 'code' => 'GD', 'name' => 'Grenada', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 90, 'code' => 'GP', 'name' => 'Guadeloupe', 'phone' => 590, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 91, 'code' => 'GU', 'name' => 'Guam', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 92, 'code' => 'GT', 'name' => 'Guatemala', 'phone' => 502, 'currency_symbol' => 'Q', 'currency' => 'GTQ'],
            ['id' => 93, 'code' => 'GG', 'name' => 'Guernsey', 'phone' => 44, 'currency_symbol' => '£', 'currency' => 'GBP'],
            ['id' => 94, 'code' => 'GN', 'name' => 'Guinea', 'phone' => 224, 'currency_symbol' => 'FG', 'currency' => 'GNF'],
            ['id' => 95, 'code' => 'GW', 'name' => 'Guinea-Bissau', 'phone' => 245, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 96, 'code' => 'GY', 'name' => 'Guyana', 'phone' => 592, 'currency_symbol' => '$', 'currency' => 'GYD'],
            ['id' => 97, 'code' => 'HT', 'name' => 'Haiti', 'phone' => 509, 'currency_symbol' => 'G', 'currency' => 'HTG'],
            ['id' => 98, 'code' => 'HM', 'name' => 'Heard Island and Mcdonald Islands', 'phone' => 61, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 99, 'code' => 'HN', 'name' => 'Honduras', 'phone' => 504, 'currency_symbol' => 'L', 'currency' => 'HNL'],
            ['id' => 100, 'code' => 'HK', 'name' => 'Hong Kong', 'phone' => 852, 'currency_symbol' => '$', 'currency' => 'HKD'],
            ['id' => 101, 'code' => 'HU', 'name' => 'Hungary', 'phone' => 36, 'currency_symbol' => 'Ft', 'currency' => 'HUF'],
            ['id' => 102, 'code' => 'IS', 'name' => 'Iceland', 'phone' => 354, 'currency_symbol' => 'kr', 'currency' => 'ISK'],
            ['id' => 103, 'code' => 'IN', 'name' => 'India', 'phone' => 91, 'currency_symbol' => '₹', 'currency' => 'INR'],
            ['id' => 104, 'code' => 'ID', 'name' => 'Indonesia', 'phone' => 62, 'currency_symbol' => 'Rp', 'currency' => 'IDR'],
            ['id' => 105, 'code' => 'IR', 'name' => 'Iran', 'phone' => 98, 'currency_symbol' => '﷼', 'currency' => 'IRR'],
            ['id' => 106, 'code' => 'IQ', 'name' => 'Iraq', 'phone' => 964, 'currency_symbol' => 'د.ع', 'currency' => 'IQD'],
            ['id' => 107, 'code' => 'IE', 'name' => 'Ireland', 'phone' => 353, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 108, 'code' => 'IM', 'name' => 'Isle of Man', 'phone' => 44, 'currency_symbol' => '£', 'currency' => 'GBP'],
            ['id' => 109, 'code' => 'IL', 'name' => 'Israel', 'phone' => 972, 'currency_symbol' => '₪', 'currency' => 'ILS'],
            ['id' => 110, 'code' => 'IT', 'name' => 'Italy', 'phone' => 39, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 111, 'code' => 'JM', 'name' => 'Jamaica', 'phone' => 1, 'currency_symbol' => 'J$', 'currency' => 'JMD'],
            ['id' => 112, 'code' => 'JP', 'name' => 'Japan', 'phone' => 81, 'currency_symbol' => '¥', 'currency' => 'JPY'],
            ['id' => 113, 'code' => 'JE', 'name' => 'Jersey', 'phone' => 44, 'currency_symbol' => '£', 'currency' => 'GBP'],
            ['id' => 114, 'code' => 'JO', 'name' => 'Jordan', 'phone' => 962, 'currency_symbol' => 'ا.د', 'currency' => 'JOD'],
            ['id' => 115, 'code' => 'KZ', 'name' => 'Kazakhstan', 'phone' => 7, 'currency_symbol' => 'лв', 'currency' => 'KZT'],
            ['id' => 116, 'code' => 'KE', 'name' => 'Kenya', 'phone' => 254, 'currency_symbol' => 'KSh', 'currency' => 'KES'],
            ['id' => 117, 'code' => 'KI', 'name' => 'Kiribati', 'phone' => 686, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 118, 'code' => 'KP', 'name' => 'Korea, North', 'phone' => 850, 'currency_symbol' => '₩', 'currency' => 'KPW'],
            ['id' => 119, 'code' => 'KR', 'name' => 'Korea, South', 'phone' => 82, 'currency_symbol' => '₩', 'currency' => 'KRW'],
            ['id' => 120, 'code' => 'XK', 'name' => 'Kosovo', 'phone' => 383, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 121, 'code' => 'KW', 'name' => 'Kuwait', 'phone' => 965, 'currency_symbol' => 'ك.د', 'currency' => 'KWD'],
            ['id' => 122, 'code' => 'KG', 'name' => 'Kyrgyzstan', 'phone' => 996, 'currency_symbol' => 'лв', 'currency' => 'KGS'],
            ['id' => 123, 'code' => 'LA', 'name' => "Lao People's Democratic Republic", 'phone' => 856, 'currency_symbol' => '₭', 'currency' => 'LAK'],
            ['id' => 124, 'code' => 'LV', 'name' => 'Latvia', 'phone' => 371, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 125, 'code' => 'LB', 'name' => 'Lebanon', 'phone' => 961, 'currency_symbol' => '£', 'currency' => 'LBP'],
            ['id' => 126, 'code' => 'LS', 'name' => 'Lesotho', 'phone' => 266, 'currency_symbol' => 'L', 'currency' => 'LSL'],
            ['id' => 127, 'code' => 'LR', 'name' => 'Liberia', 'phone' => 231, 'currency_symbol' => '$', 'currency' => 'LRD'],
            ['id' => 128, 'code' => 'LY', 'name' => 'Libya', 'phone' => 218, 'currency_symbol' => 'د.ل', 'currency' => 'LYD'],
            ['id' => 129, 'code' => 'LI', 'name' => 'Liechtenstein', 'phone' => 423, 'currency_symbol' => 'CHf', 'currency' => 'CHF'],
            ['id' => 130, 'code' => 'LT', 'name' => 'Lithuania', 'phone' => 370, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 131, 'code' => 'LU', 'name' => 'Luxembourg', 'phone' => 352, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 132, 'code' => 'MO', 'name' => 'Macao', 'phone' => 853, 'currency_symbol' => '$', 'currency' => 'MOP'],
            ['id' => 133, 'code' => 'MK', 'name' => 'Macedonia North', 'phone' => 389, 'currency_symbol' => 'ден', 'currency' => 'MKD'],
            ['id' => 134, 'code' => 'MG', 'name' => 'Madagascar', 'phone' => 261, 'currency_symbol' => 'Ar', 'currency' => 'MGA'],
            ['id' => 135, 'code' => 'MW', 'name' => 'Malawi', 'phone' => 265, 'currency_symbol' => 'MK', 'currency' => 'MWK'],
            ['id' => 136, 'code' => 'MY', 'name' => 'Malaysia', 'phone' => 60, 'currency_symbol' => 'RM', 'currency' => 'MYR'],
            ['id' => 137, 'code' => 'MV', 'name' => 'Maldives', 'phone' => 960, 'currency_symbol' => 'Rf', 'currency' => 'MVR'],
            ['id' => 138, 'code' => 'ML', 'name' => 'Mali', 'phone' => 223, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 139, 'code' => 'MT', 'name' => 'Malta', 'phone' => 356, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 140, 'code' => 'MH', 'name' => 'Marshall Islands', 'phone' => 692, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 141, 'code' => 'MQ', 'name' => 'Martinique', 'phone' => 596, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 142, 'code' => 'MR', 'name' => 'Mauritania', 'phone' => 222, 'currency_symbol' => 'MRU', 'currency' => 'MRO'],
            ['id' => 143, 'code' => 'MU', 'name' => 'Mauritius', 'phone' => 230, 'currency_symbol' => '₨', 'currency' => 'MUR'],
            ['id' => 144, 'code' => 'YT', 'name' => 'Mayotte', 'phone' => 262, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 145, 'code' => 'MX', 'name' => 'Mexico', 'phone' => 52, 'currency_symbol' => '$', 'currency' => 'MXN'],
            ['id' => 146, 'code' => 'FM', 'name' => 'Micronesia', 'phone' => 691, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 147, 'code' => 'MD', 'name' => 'Moldova', 'phone' => 373, 'currency_symbol' => 'L', 'currency' => 'MDL'],
            ['id' => 148, 'code' => 'MC', 'name' => 'Monaco', 'phone' => 377, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 149, 'code' => 'MN', 'name' => 'Mongolia', 'phone' => 976, 'currency_symbol' => '₮', 'currency' => 'MNT'],
            ['id' => 150, 'code' => 'ME', 'name' => 'Montenegro', 'phone' => 382, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 151, 'code' => 'MS', 'name' => 'Montserrat', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 152, 'code' => 'MA', 'name' => 'Morocco', 'phone' => 212, 'currency_symbol' => 'DH', 'currency' => 'MAD'],
            ['id' => 153, 'code' => 'MZ', 'name' => 'Mozambique', 'phone' => 258, 'currency_symbol' => 'MT', 'currency' => 'MZN'],
            ['id' => 154, 'code' => 'MM', 'name' => 'Myanmar (Burma)', 'phone' => 95, 'currency_symbol' => 'K', 'currency' => 'MMK'],
            ['id' => 155, 'code' => 'NA', 'name' => 'Namibia', 'phone' => 264, 'currency_symbol' => '$', 'currency' => 'NAD'],
            ['id' => 156, 'code' => 'NR', 'name' => 'Nauru', 'phone' => 674, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 157, 'code' => 'NP', 'name' => 'Nepal', 'phone' => 977, 'currency_symbol' => '₨', 'currency' => 'NPR'],
            ['id' => 158, 'code' => 'NL', 'name' => 'Netherlands', 'phone' => 31, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 159, 'code' => 'AN', 'name' => 'Netherlands Antilles', 'phone' => 599, 'currency_symbol' => 'NAf', 'currency' => 'ANG'],
            ['id' => 160, 'code' => 'NC', 'name' => 'New Caledonia', 'phone' => 687, 'currency_symbol' => '₣', 'currency' => 'XPF'],
            ['id' => 161, 'code' => 'NZ', 'name' => 'New Zealand', 'phone' => 64, 'currency_symbol' => '$', 'currency' => 'NZD'],
            ['id' => 162, 'code' => 'NI', 'name' => 'Nicaragua', 'phone' => 505, 'currency_symbol' => 'C$', 'currency' => 'NIO'],
            ['id' => 163, 'code' => 'NE', 'name' => 'Niger', 'phone' => 227, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 164, 'code' => 'NG', 'name' => 'Nigeria', 'phone' => 234, 'currency_symbol' => '₦', 'currency' => 'NGN'],
            ['id' => 165, 'code' => 'NU', 'name' => 'Niue', 'phone' => 683, 'currency_symbol' => '$', 'currency' => 'NZD'],
            ['id' => 166, 'code' => 'NF', 'name' => 'Norfolk Island', 'phone' => 672, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 167, 'code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 168, 'code' => 'NO', 'name' => 'Norway', 'phone' => 47, 'currency_symbol' => 'kr', 'currency' => 'NOK'],
            ['id' => 169, 'code' => 'OM', 'name' => 'Oman', 'phone' => 968, 'currency_symbol' => '.ع.ر', 'currency' => 'OMR'],
            ['id' => 170, 'code' => 'PK', 'name' => 'Pakistan', 'phone' => 92, 'currency_symbol' => '₨', 'currency' => 'PKR'],
            ['id' => 171, 'code' => 'PW', 'name' => 'Palau', 'phone' => 680, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 172, 'code' => 'PS', 'name' => 'Palestine', 'phone' => 970, 'currency_symbol' => '₪', 'currency' => 'ILS'],
            ['id' => 173, 'code' => 'PA', 'name' => 'Panama', 'phone' => 507, 'currency_symbol' => 'B/.', 'currency' => 'PAB'],
            ['id' => 174, 'code' => 'PG', 'name' => 'Papua New Guinea', 'phone' => 675, 'currency_symbol' => 'K', 'currency' => 'PGK'],
            ['id' => 175, 'code' => 'PY', 'name' => 'Paraguay', 'phone' => 595, 'currency_symbol' => '₲', 'currency' => 'PYG'],
            ['id' => 176, 'code' => 'PE', 'name' => 'Peru', 'phone' => 51, 'currency_symbol' => 'S/.', 'currency' => 'PEN'],
            ['id' => 177, 'code' => 'PH', 'name' => 'Philippines', 'phone' => 63, 'currency_symbol' => '₱', 'currency' => 'PHP'],
            ['id' => 178, 'code' => 'PN', 'name' => 'Pitcairn Islands', 'phone' => 64, 'currency_symbol' => '$', 'currency' => 'NZD'],
            ['id' => 179, 'code' => 'PL', 'name' => 'Poland', 'phone' => 48, 'currency_symbol' => 'zł', 'currency' => 'PLN'],
            ['id' => 180, 'code' => 'PT', 'name' => 'Portugal', 'phone' => 351, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 181, 'code' => 'PR', 'name' => 'Puerto Rico', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 182, 'code' => 'QA', 'name' => 'Qatar', 'phone' => 974, 'currency_symbol' => 'ق.ر', 'currency' => 'QAR'],
            ['id' => 183, 'code' => 'RE', 'name' => 'Reunion', 'phone' => 262, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 184, 'code' => 'RO', 'name' => 'Romania', 'phone' => 40, 'currency_symbol' => 'lei', 'currency' => 'RON'],
            ['id' => 185, 'code' => 'RU', 'name' => 'Russian Federation', 'phone' => 7, 'currency_symbol' => '₽', 'currency' => 'RUB'],
            ['id' => 186, 'code' => 'RW', 'name' => 'Rwanda', 'phone' => 250, 'currency_symbol' => 'FRw', 'currency' => 'RWF'],
            ['id' => 187, 'code' => 'BL', 'name' => 'Saint Barthelemy', 'phone' => 590, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 188, 'code' => 'SH', 'name' => 'Saint Helena', 'phone' => 290, 'currency_symbol' => '£', 'currency' => 'SHP'],
            ['id' => 189, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 190, 'code' => 'LC', 'name' => 'Saint Lucia', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 191, 'code' => 'MF', 'name' => 'Saint Martin', 'phone' => 590, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 192, 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phone' => 508, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 193, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'XCD'],
            ['id' => 194, 'code' => 'WS', 'name' => 'Samoa', 'phone' => 685, 'currency_symbol' => 'SAT', 'currency' => 'WST'],
            ['id' => 195, 'code' => 'SM', 'name' => 'San Marino', 'phone' => 378, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 196, 'code' => 'ST', 'name' => 'Sao Tome and Principe', 'phone' => 239, 'currency_symbol' => 'Db', 'currency' => 'STD'],
            ['id' => 197, 'code' => 'SA', 'name' => 'Saudi Arabia', 'phone' => 966, 'currency_symbol' => '﷼', 'currency' => 'SAR'],
            ['id' => 198, 'code' => 'SN', 'name' => 'Senegal', 'phone' => 221, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 199, 'code' => 'RS', 'name' => 'Serbia', 'phone' => 381, 'currency_symbol' => 'din', 'currency' => 'RSD'],
            ['id' => 200, 'code' => 'CS', 'name' => 'Serbia and Montenegro', 'phone' => 381, 'currency_symbol' => 'din', 'currency' => 'RSD'],
            ['id' => 201, 'code' => 'SC', 'name' => 'Seychelles', 'phone' => 248, 'currency_symbol' => 'SRe', 'currency' => 'SCR'],
            ['id' => 202, 'code' => 'SL', 'name' => 'Sierra Leone', 'phone' => 232, 'currency_symbol' => 'Le', 'currency' => 'SLL'],
            ['id' => 203, 'code' => 'SG', 'name' => 'Singapore', 'phone' => 65, 'currency_symbol' => '$', 'currency' => 'SGD'],
            ['id' => 204, 'code' => 'SX', 'name' => 'Sint Maarten', 'phone' => 1, 'currency_symbol' => 'ƒ', 'currency' => 'ANG'],
            ['id' => 205, 'code' => 'SK', 'name' => 'Slovakia', 'phone' => 421, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 206, 'code' => 'SI', 'name' => 'Slovenia', 'phone' => 386, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 207, 'code' => 'SB', 'name' => 'Solomon Islands', 'phone' => 677, 'currency_symbol' => 'Si$', 'currency' => 'SBD'],
            ['id' => 208, 'code' => 'SO', 'name' => 'Somalia', 'phone' => 252, 'currency_symbol' => 'Sh.so.', 'currency' => 'SOS'],
            ['id' => 209, 'code' => 'ZA', 'name' => 'South Africa', 'phone' => 27, 'currency_symbol' => 'R', 'currency' => 'ZAR'],
            ['id' => 210, 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'phone' => 500, 'currency_symbol' => '£', 'currency' => 'GBP'],
            ['id' => 211, 'code' => 'SS', 'name' => 'South Sudan', 'phone' => 211, 'currency_symbol' => '£', 'currency' => 'SSP'],
            ['id' => 212, 'code' => 'ES', 'name' => 'Spain', 'phone' => 34, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 213, 'code' => 'LK', 'name' => 'Sri Lanka', 'phone' => 94, 'currency_symbol' => 'Rs', 'currency' => 'LKR'],
            ['id' => 214, 'code' => 'SD', 'name' => 'Sudan', 'phone' => 249, 'currency_symbol' => '.س.ج', 'currency' => 'SDG'],
            ['id' => 215, 'code' => 'SR', 'name' => 'Suriname', 'phone' => 597, 'currency_symbol' => '$', 'currency' => 'SRD'],
            ['id' => 216, 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'phone' => 47, 'currency_symbol' => 'kr', 'currency' => 'NOK'],
            ['id' => 217, 'code' => 'SE', 'name' => 'Sweden', 'phone' => 46, 'currency_symbol' => 'kr', 'currency' => 'SEK'],
            ['id' => 218, 'code' => 'CH', 'name' => 'Switzerland', 'phone' => 41, 'currency_symbol' => 'CHf', 'currency' => 'CHF'],
            ['id' => 219, 'code' => 'SY', 'name' => 'Syria', 'phone' => 963, 'currency_symbol' => 'LS', 'currency' => 'SYP'],
            ['id' => 220, 'code' => 'TW', 'name' => 'Taiwan', 'phone' => 886, 'currency_symbol' => '$', 'currency' => 'TWD'],
            ['id' => 221, 'code' => 'TJ', 'name' => 'Tajikistan', 'phone' => 992, 'currency_symbol' => 'SM', 'currency' => 'TJS'],
            ['id' => 222, 'code' => 'TZ', 'name' => 'Tanzania', 'phone' => 255, 'currency_symbol' => 'TSh', 'currency' => 'TZS'],
            ['id' => 223, 'code' => 'TH', 'name' => 'Thailand', 'phone' => 66, 'currency_symbol' => '฿', 'currency' => 'THB'],
            ['id' => 224, 'code' => 'TL', 'name' => 'Timor-Leste', 'phone' => 670, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 225, 'code' => 'TG', 'name' => 'Togo', 'phone' => 228, 'currency_symbol' => 'CFA', 'currency' => 'XOF'],
            ['id' => 226, 'code' => 'TK', 'name' => 'Tokelau', 'phone' => 690, 'currency_symbol' => '$', 'currency' => 'NZD'],
            ['id' => 227, 'code' => 'TO', 'name' => 'Tonga', 'phone' => 676, 'currency_symbol' => '$', 'currency' => 'TOP'],
            ['id' => 228, 'code' => 'TT', 'name' => 'Trinidad and Tobago', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'TTD'],
            ['id' => 229, 'code' => 'TN', 'name' => 'Tunisia', 'phone' => 216, 'currency_symbol' => 'ت.د', 'currency' => 'TND'],
            ['id' => 230, 'code' => 'TR', 'name' => 'Turkey (Türkiye)', 'phone' => 90, 'currency_symbol' => '₺', 'currency' => 'TRY'],
            ['id' => 231, 'code' => 'TM', 'name' => 'Turkmenistan', 'phone' => 993, 'currency_symbol' => 'T', 'currency' => 'TMT'],
            ['id' => 232, 'code' => 'TC', 'name' => 'Turks and Caicos Islands', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 233, 'code' => 'TV', 'name' => 'Tuvalu', 'phone' => 688, 'currency_symbol' => '$', 'currency' => 'AUD'],
            ['id' => 234, 'code' => 'UM', 'name' => 'U.S. Outlying Islands', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 235, 'code' => 'UG', 'name' => 'Uganda', 'phone' => 256, 'currency_symbol' => 'USh', 'currency' => 'UGX'],
            ['id' => 236, 'code' => 'UA', 'name' => 'Ukraine', 'phone' => 380, 'currency_symbol' => '₴', 'currency' => 'UAH'],
            ['id' => 237, 'code' => 'AE', 'name' => 'United Arab Emirates', 'phone' => 971, 'currency_symbol' => 'إ.د', 'currency' => 'AED'],
            ['id' => 238, 'code' => 'GB', 'name' => 'United Kingdom', 'phone' => 44, 'currency_symbol' => '£', 'currency' => 'GBP'],
            ['id' => 239, 'code' => 'US', 'name' => 'United States', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 240, 'code' => 'UY', 'name' => 'Uruguay', 'phone' => 598, 'currency_symbol' => '$', 'currency' => 'UYU'],
            ['id' => 241, 'code' => 'UZ', 'name' => 'Uzbekistan', 'phone' => 998, 'currency_symbol' => 'лв', 'currency' => 'UZS'],
            ['id' => 242, 'code' => 'VU', 'name' => 'Vanuatu', 'phone' => 678, 'currency_symbol' => 'VT', 'currency' => 'VUV'],
            ['id' => 243, 'code' => 'VA', 'name' => 'Vatican City Holy See', 'phone' => 39, 'currency_symbol' => '€', 'currency' => 'EUR'],
            ['id' => 244, 'code' => 'VE', 'name' => 'Venezuela', 'phone' => 58, 'currency_symbol' => 'Bs', 'currency' => 'VEF'],
            ['id' => 245, 'code' => 'VN', 'name' => 'Vietnam', 'phone' => 84, 'currency_symbol' => '₫', 'currency' => 'VND'],
            ['id' => 246, 'code' => 'VG', 'name' => 'Virgin Islands, British', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 247, 'code' => 'VI', 'name' => 'Virgin Islands, U.S', 'phone' => 1, 'currency_symbol' => '$', 'currency' => 'USD'],
            ['id' => 248, 'code' => 'WF', 'name' => 'Wallis and Futuna', 'phone' => 681, 'currency_symbol' => '₣', 'currency' => 'XPF'],
            ['id' => 249, 'code' => 'EH', 'name' => 'Western Sahara', 'phone' => 212, 'currency_symbol' => 'MAD', 'currency' => 'MAD'],
            ['id' => 250, 'code' => 'YE', 'name' => 'Yemen', 'phone' => 967, 'currency_symbol' => '﷼', 'currency' => 'YER'],
            ['id' => 251, 'code' => 'ZM', 'name' => 'Zambia', 'phone' => 260, 'currency_symbol' => 'ZK', 'currency' => 'ZMW'],
            ['id' => 252, 'code' => 'ZW', 'name' => 'Zimbabwe', 'phone' => 263, 'currency_symbol' => '$', 'currency' => 'ZWL'],
        ];

        foreach (array_chunk($countries, 50) as $chunk) {
            DB::table('countries')->insert($chunk);
        }
    }
}
